from BaseClasses import Location
import typing


class AdvData(typing.NamedTuple):
    id: typing.Optional[int]
    region: str


class UndertaleYellowAdvancement(Location):
    game: str = "Undertale Yellow"

advancement_table = {
    "Lemonade Stand": AdvData(96500, "Ruins"),
    "Candy Corn": AdvData(96501, "Ruins"),
    "Pebble Pile": AdvData(96502, "Ruins"),
    "Stray Feather": AdvData(96503, "Ruins"),
    "Corn Dog": AdvData(96504, "Ruins"),
    "Golden Pear": AdvData(96505, "Ruins"),
    "Dalv's Fridge": AdvData(96506, "Ruins"),
    "Ice Pellets": AdvData(96507, "Snowdin"),
    "Mo Snowdin 1": AdvData(96508, "Snowdin"),
    "Mo Snowdin 2": AdvData(96509, "Snowdin"),
    "Mo Snowdin 3": AdvData(96510, "Snowdin"),
    "Honeydew Inn Shop 1": AdvData(96511, "Snowdin"),
    "Honeydew Inn Shop 2": AdvData(96512, "Snowdin"),
    "Honeydew Inn Shop 3": AdvData(96513, "Snowdin"),
    "Honeydew Inn Shop 4": AdvData(96514, "Snowdin"),
    "Favorite Song Fan": AdvData(96515, "Snowdin"),
    "Golden Coffee": AdvData(96516, "Snowdin"),
    "Coffee Trade": AdvData(96517, "Snowdin"),
    "Mitten Trade": AdvData(96518, "Snowdin"),
    "Map Trade": AdvData(96519, "Snowdin"),
    "Matches Trade": AdvData(96520, "Snowdin"),
    "Scarf Trade": AdvData(96521, "Snowdin"),
    "Coffee Bean Barrel": AdvData(96522, "Snowdin"),
    "Bench Pancakes": AdvData(96523, "Snowdin"),
    "Trail Mix Chest": AdvData(96524, "Dunes West"),
    "Packing Peanuts": AdvData(96525, "Dunes West"),
    "Mo Dunes 1": AdvData(96526, "Dunes West"),
    "Mo Dunes 2": AdvData(96527, "Dunes West"),
    "Mo Dunes 3": AdvData(96528, "Dunes West"),
    "Flint Pile": AdvData(96529, "Dunes West"),
    "Steel Buckle Candy": AdvData(96530, "Dunes West"),
    "Pickaxe": AdvData(96531, "Dunes West"),
    "Saftey Jacket Hanger": AdvData(96532, "Dunes East"),
    "Stale Fruitcake": AdvData(96533, "Dunes East"),
    "Gift Shop Mug": AdvData(96534, "Dunes East"),
    "Spider Bake Sale": AdvData(96535, "Dunes East"),
    "Pants Pocket Robbery": AdvData(96536, "Dunes East"),
    "Dunes Barkeep 1": AdvData(96537, "Dunes East"),
    "Dunes Barkeep 2": AdvData(96538, "Dunes East"),
    "Dunes Barkeep 3": AdvData(96539, "Dunes East"),
    "Dunes Barkeep 4": AdvData(96540, "Dunes East"),
    "Dunes Gunsmith 1": AdvData(96541, "Dunes East"),
    "Dunes Gunsmith 2": AdvData(96542, "Dunes East"),
    "Dunes Gunsmith 3": AdvData(96543, "Dunes East"),
    "Wild Revolver": AdvData(96544, "Dunes East"),
    "Nice Hat": AdvData(96545, "Dunes East"),
    "Broken Necklace": AdvData(96546, "Dunes East"),
    "Golden Cactus": AdvData(96547, "Dunes East"),
    "Genocide Friendliness Pellets": AdvData(96548, "Dunes East"),
    "Washing Machine Beef Jerky": AdvData(96549, "Steamworks Entrance"),
    "Golden Bandana": AdvData(96550, "Steamworks Entrance"),
    "Mo Steamworks 1": AdvData(96551, "Steamworks Entrance"),
    "Mo Steamworks 2": AdvData(96552, "Steamworks Entrance"),
    "Mo Steamworks 3": AdvData(96553, "Steamworks Entrance"),
    "Vendy Shop 1": AdvData(96554, "Steamworks Entrance"),
    "Vendy Shop 2": AdvData(96555, "Steamworks Entrance"),
    "Vendy Shop 3": AdvData(96556, "Steamworks Entrance"),
    "Vendy Shop 4": AdvData(96557, "Steamworks Entrance"),
    "Box of Nails": AdvData(96558, "Steamworks Entrance"),
    "Box of Fries": AdvData(96559, "Steamworks Entrance"),
    "Box of Granola": AdvData(96560, "Steamworks Entrance"),
    "Trash Can Beef Jerky": AdvData(96561, "Steamworks Pacifist"),
    "Broken Vending Machine": AdvData(96562, "Steamworks Axis"),
    "Closet Water": AdvData(965563, "Steamworks Neutral"),
    "Cake": AdvData(965564, "Steamworks Neutral"),
    "Hydrochloric Acid": AdvData(965565, "Steamworks Neutral"),
    "Neutral Friendliness Pellets": AdvData(965566, "Steamworks Axis"),
    "Ceroba's Fridge": AdvData(965567, "Ketsukane Manor"),
    "Hidden Tape": AdvData(965568, "Ketsukane Manor"),
    "Bits & Bytes Shop 1": AdvData(965569, "Hotland"),
    "Bits & Bytes Shop 2": AdvData(965570, "Hotland"),
    "Bits & Bytes Shop 3": AdvData(965571, "Hotland"),
    "Bits & Bytes Shop 4": AdvData(965572, "Hotland"),
    "Trash Can Hot Dog": AdvData(965573, "Hotland"),
    "Trash Can Monster Candy": AdvData(965574, "Hotland"),
    "Bench Chisps": AdvData(965575, "New Home"),
    "Trash Can Soda": AdvData(965576, "New Home"),
}

exclusion_table = {
    "pacifist": {
        "Dunes Barkeep 2",
        "Genocide Friendliness Pellets",
        "Closet Water",
        "Cake",
        "Hydrochloric Acid",
        "Neutral Friendliness Pellets",
    },
    "neutral": {
        "Dunes Barkeep 2",
        "Genocide Friendliness Pellets",
        "Trash Can Beef Jerky",
        "Ceroba's Fridge",
        "Hidden Tape",
        "Bench Chisps",
        "Trash Can Soda",
    },
    "genocide": {
        "Broken Necklace",
        "Trash Can Beef Jerky",
        "Neutral Friendliness Pellets",
        "Ceroba's Fridge",
        "Hidden Tape",
    }
}
